global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "simulator"
    static_configs:
      - targets: ['simulator:8000']
