name: Build and Deploy Next.js App

on:
  push:
    branches:
      - feat-retries

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image api
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tcc_toleranciafalhas_api:featRetries

      - name: Build and push Docker image simulator
        uses: docker/build-push-action@v4
        with:
          context: ./simulator
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tcc_toleranciafalhas_simulator:featRetries

      - name: Build and push Docker image simulator
        uses: docker/build-push-action@v4
        with:
          context: ./receiver
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tcc_toleranciafalhas_receiver:featRetries